### ISSUE TITLE
Tiff image issues

### ISSUE THREAD

**Issue by zysno1** [TesterTi/LIDCToolbox#2]
First of all, thank you very much for your toolbox!

I have setup matlab + lidcToolbox on my local computer. I have convert a little LIDC directory via this toolbox. But I found the tiff which be converted is black via windows photo viewer.

I don't know what cause this, waiting for help:)

PS: What application should I use to view these tiff?

**Comment by TesterTi** [comment]
I'm glad to hear that the toolbox is helpful.

Are you converting the masks? If so, this would be expected because their values are binary (0s and 1s), which photo viewer probably interprets as black.

I'd recommend loading the tiffs in Matlab if you have it, then using the 'imagesc' command to display them (which automatically scales the image values).

**Comment by zysno1** [comment]
Thanks for your response! 

I will try it as your notice right now, then feedback result. Thanks again:)

**Comment by TesterTi** [comment]
I've just updated the toolbox to include some sample outputs. These should help you to validate your installation (please see the readme's validation section for more information).
