### ISSUE TITLE
Missing GTs

### ISSUE THREAD

**Issue by stefanknegt** [TesterTi/LIDCToolbox#6]
First of all, thanks for making this toolbox! I have a question regarding the difference between an empty .tif file in the gts folder and missing .tif files. 
For instance, in sample_output/gts/191425307197546732281885591780/slice1/ there are 3 (out of 4) .tif files which only contain zeros. When looking at the corresponding .xml we also see that only in the last readingSession there is an entry for this imageZposition. However, in sample_output/gts/490157381160200744295382098329/slice1/ there are only two .tif files. What is the reason that sometimes the script adds empty (containing only zeros) .tif files in the gts folder while in other cases it does not?

**Comment by TesterTi** [comment]
Hi, and thank you for using it!

In sample_output/gts/490157381160200744295382098329 there are two GTs because there are only two annotations in the xml (there are in fact 4 'readingSessions' in the xml but the first two only contain annotations for small nodules, <= 3mm, which are ignored by the toolbox).

In sample_output/gts/191425307197546732281885591780 there are 4 annotations because all annotators marked at least one large nodule in at least one slice of the scan. If this is the case it is assumed that the annotator inspected all slices of the scan but did not find anything to annotate in some, so the toolbox creates a blank GTs for these slices.

Does that clear things up?

**Comment by stefanknegt** [comment]
Yes, thank you very much for the clarification. I have another question, I hope it is ok that I ask this here. In the XML file there are also nodules < 3mm annotated and non-nodules > 3mm annotated, but in a different manner in which only a single point is given (the center). Do you ignore these cases or are they included in the output?

**Comment by stefanknegt** [comment]
Yes it does, thanks a lot!
