### ISSUE TITLE
Strange output for around 120 cases with Toshiba scanners

### ISSUE THREAD

**Issue by stefanknegt** [TesterTi/LIDCToolbox#9]
I've found out that there is still something strange happening with Toshiba scans. This is for instance case LIDC-IDRI-0892. Where one (000042.dcm)of the original dicom files looks like this:
![screenshot 2018-12-20 at 09 22 16](https://user-images.githubusercontent.com/17021755/50272771-1399bc00-0439-11e9-9297-9020dc9968bc.png)

And for this image, the output of the Toolbox is:
![screenshot 2018-12-20 at 09 20 41](https://user-images.githubusercontent.com/17021755/50272748-07156380-0439-11e9-958f-23b79e452f02.png)

There seems to be something strange happening due to the fact that there are a lot of negative pixel values in the original image. As you can see in this histogram:
![hist](https://user-images.githubusercontent.com/17021755/50272859-607d9280-0439-11e9-883e-123179539b51.png)

Could this be caused by the following messages the toolbox gives when processing this patient:
_Warning: No padding value found. If negative values are found in the image then these will be used for the mask, if not, the mask will be empty_ ?

**Comment by TesterTi** [comment]
Hi, yes that should be the problem (I assume the mask image is also not correct). Normally the DICOM metadata should list the padding value but if that is not found then the toolbox assumes that the minimum pixel value represents masked locations (perhaps this should be changed, or at least require more explicit user consent before proceeding, I won't have any time to implement this for a few weeks though).

Do you know if the padding value is consistent across the scans in your dataset? If so, it would be very simple to hard code it (see lines 170 to 177 in LIDC_mat_2_mask.m). If it is not consistent then it will require manual analysis of each image to determine their padding values (or simply turn the option off by setting the mask value to something unrealistic, e.g. Inf).

**Comment by stefanknegt** [comment]
Thanks for your response. What I've found so far is that commenting out lines 184-186 of LIDC_mat_2_mask.m (shown below) solves this problem. 
```
if isfield(dicomInfo, 'PixelPaddingValue')
  img_bw(img_bw == dicomInfo.PixelPaddingValue) = 0;
end
```
However, then the output for the cases without negative pixel values becomes wrong. So I was wondering whether you have a solution that would work for this problem?

**Comment by TesterTi** [comment]
Yes, that will generally resolve the problem for the case when there are necessary negative values in the image and no padding value defined. However, I'm just writing this in case someone else stumbles across the same problem, the masks generated will not be valid.

I assume then that the images without negative pixels have a padding value (otherwise what you've commented shouldn't make any difference to them), or maybe they have negative values but that it indeed the padding value, even if not defined in the metadata?  Either way, you'd need to change condition on line 179 to allow those cases but ignore the cases when the image has (true) negative values.

**Comment by stefanknegt** [comment]
Line 179 only changes the mask, but if you check the images when you comment out the 3 lines I suggested, the images are also no longer valid. So I assume I need to do more than only changing the condition on line 179 to properly deal with this right?

Also, I have checked and PixelPaddingValue is not given for the images containing a lot of negative pixel values.

**Comment by TesterTi** [comment]
My mistake, I meant to say to edit the condition in line 184 that you commented.

And is the PixelPaddingValue given for images that do not contain negative pixel values?

If you don't get it fixed in the next couple of weeks I can take a deeper look but it should be relatively simple to add a condition to deal with the cases. Let me know what you find...

**Comment by stefanknegt** [comment]
I ended up checking whether the manufacturer was not equal to Toshiba on line 184.

I, however, also found that sometimes there are negative pixel values for a different manufacturer. I've checked all these resulting images and they look good, so apparently it only goes wrong with Toshiba scans (maybe because they have so many negative values).
